[package]
name = "vacua-scan"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
vacua-core = { path = "../vacua-core" }
serde = { workspace = true }
walkdir = { workspace = true }
libc = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
