use schemars::schema_for;
use serde_json::Value;
use std::collections::BTreeMap;

use crate::dto::*;

/// Generate a map of filename to JSON Schema value for all public DTOs.
pub fn generate_all_schemas() -> BTreeMap<&'static str, Value> {
    let mut map = BTreeMap::new();

    map.insert(
        "storage-summary-v1.schema.json",
        serde_json::to_value(schema_for!(StorageSummaryV1)).unwrap(),
    );
    map.insert(
        "candidate-summary-v1.schema.json",
        serde_json::to_value(schema_for!(CandidateSummaryV1)).unwrap(),
    );
    map.insert(
        "candidate-list-v1.schema.json",
        serde_json::to_value(schema_for!(CandidateListResponseV1)).unwrap(),
    );
    map.insert(
        "candidate-detail-v1.schema.json",
        serde_json::to_value(schema_for!(CandidateDetailV1)).unwrap(),
    );
    map.insert(
        "snapshot-summary-v1.schema.json",
        serde_json::to_value(schema_for!(SnapshotSummaryV1)).unwrap(),
    );
    map.insert(
        "snapshot-list-v1.schema.json",
        serde_json::to_value(schema_for!(SnapshotListResponseV1)).unwrap(),
    );
    map.insert(
        "snapshot-detail-v1.schema.json",
        serde_json::to_value(schema_for!(SnapshotDetailV1)).unwrap(),
    );
    map.insert(
        "snapshot-diff-v1.schema.json",
        serde_json::to_value(schema_for!(SnapshotDiffV1)).unwrap(),
    );
    map.insert(
        "application-summary-v1.schema.json",
        serde_json::to_value(schema_for!(ApplicationSummaryV1)).unwrap(),
    );
    map.insert(
        "application-list-v1.schema.json",
        serde_json::to_value(schema_for!(ApplicationListResponseV1)).unwrap(),
    );
    map.insert(
        "application-detail-v1.schema.json",
        serde_json::to_value(schema_for!(ApplicationDetailV1)).unwrap(),
    );
    map.insert(
        "duplicate-group-v1.schema.json",
        serde_json::to_value(schema_for!(DuplicateGroupSummaryV1)).unwrap(),
    );
    map.insert(
        "duplicate-list-v1.schema.json",
        serde_json::to_value(schema_for!(DuplicateListResponseV1)).unwrap(),
    );
    map.insert(
        "duplicate-detail-v1.schema.json",
        serde_json::to_value(schema_for!(DuplicateGroupDetailV1)).unwrap(),
    );
    map.insert(
        "cleanup-simulation-v1.schema.json",
        serde_json::to_value(schema_for!(CleanupSimulationV1)).unwrap(),
    );
    map.insert(
        "plan-proposal-v1.schema.json",
        serde_json::to_value(schema_for!(CleanupPlanProposalV1)).unwrap(),
    );
    map.insert(
        "server-capabilities-v1.schema.json",
        serde_json::to_value(schema_for!(ServerCapabilitiesV1)).unwrap(),
    );
    map.insert(
        "history-summary-v1.schema.json",
        serde_json::to_value(schema_for!(HistorySummaryV1)).unwrap(),
    );
    map.insert(
        "history-verification-v1.schema.json",
        serde_json::to_value(schema_for!(HistoryVerificationV1)).unwrap(),
    );
    map.insert(
        "build-info-v1.schema.json",
        serde_json::to_value(schema_for!(BuildInfoV1)).unwrap(),
    );
    map.insert(
        "release-manifest-v1.schema.json",
        serde_json::to_value(schema_for!(ReleaseManifestV1)).unwrap(),
    );
    map.insert(
        "storage-tree-analysis-v1.schema.json",
        serde_json::to_value(schema_for!(StorageTreeAnalysisV1)).unwrap(),
    );
    map.insert(
        "storage-tree-page-v1.schema.json",
        serde_json::to_value(schema_for!(StorageTreePageV1)).unwrap(),
    );
    map.insert(
        "storage-tree-node-detail-v1.schema.json",
        serde_json::to_value(schema_for!(StorageTreeNodeDetailV1)).unwrap(),
    );
    map.insert(
        "developer-artifact-analysis-v1.schema.json",
        serde_json::to_value(schema_for!(DeveloperArtifactAnalysisV1)).unwrap(),
    );
    map.insert(
        "developer-project-summary-v1.schema.json",
        serde_json::to_value(schema_for!(DeveloperProjectSummaryV1)).unwrap(),
    );
    map.insert(
        "developer-project-detail-v1.schema.json",
        serde_json::to_value(schema_for!(DeveloperProjectDetailV1)).unwrap(),
    );
    map.insert(
        "developer-artifact-summary-v1.schema.json",
        serde_json::to_value(schema_for!(DeveloperArtifactSummaryV1)).unwrap(),
    );
    map.insert(
        "developer-artifact-detail-v1.schema.json",
        serde_json::to_value(schema_for!(DeveloperArtifactDetailV1)).unwrap(),
    );
    map.insert(
        "rebuild-evidence-v1.schema.json",
        serde_json::to_value(schema_for!(RebuildEvidenceV1)).unwrap(),
    );
    map.insert(
        "developer-artifact-coverage-v1.schema.json",
        serde_json::to_value(schema_for!(DeveloperArtifactCoverageV1)).unwrap(),
    );
    map.insert(
        "developer-artifact-page-v1.schema.json",
        serde_json::to_value(schema_for!(DeveloperArtifactPageV1)).unwrap(),
    );

    map
}
